### ISSUE TITLE
Add an option to set download speed/bandwidth limit

### ISSUE THREAD

**Issue by Xyde** [AlexAplin/nndownload#103]
I tried limiting the threads that nndownload uses but it's still using half of my internet speed and not making much difference (because my upload/download is low to start with). Would it be possible to add this feature?

**Comment by AlexAplin** [comment]
This would require a deep reimplementation of the requests function. I'll see what's reasonable but don't count on anything being added soon. I'd recommend a third-party utility like [NetLimiter](https://www.netlimiter.com/).

**Comment by AlexAplin** [comment]
Not implementing this for now.
