### ISSUE TITLE
error when download private video

### ISSUE THREAD

**Issue by Cathgao** [AlexAplin/nndownload#110]
using cookie to download an private video return `FormatNotAvailableException`. I have the permission to watch the video, and can using IDM to download, but failed with nndownload
```
Using provided session cookie.
Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1697, in main
  File "nndownload\nndownload.py", line 1656, in process_url_mo
  File "nndownload\nndownload.py", line 923, in request_video
FormatNotAvailableException: Could not retrieve video info. This video may have been deleted
```

**Comment by AlexAplin** [comment]
Private videos are typically not able to be viewed by anyone other than the uploader. Is there a different type of private video on Nico?

**Comment by AlexAplin** [comment]
Closing for now.
