### ISSUE TITLE
KeyError: 'thumbnailURL'

### ISSUE THREAD

**Issue by cleartonic** [AlexAplin/nndownload#112]
The following error occurs on the sample URL/code in the readme, after using -u/-p instead of -g to properly authenticate:

```
Logging in...
Logged in.
Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\site-packages\nndownload\nndownload.py", line 1329, in main
    process_url_mo(session, url_mo)
  File "C:\Users\Anaconda3\lib\site-packages\nndownload\nndownload.py", line 1293, in process_url_mo
    request_video(session, url_id)
  File "C:\Users\Anaconda3\lib\site-packages\nndownload\nndownload.py", line 639, in request_video
    template_params = perform_api_request(session, document)
  File "C:\Users\Anaconda3\lib\site-packages\nndownload\nndownload.py", line 947, in perform_api_request
    template_params = collect_parameters(session, template_params, params, is_html5=True)
  File "C:\Users\Anaconda3\lib\site-packages\nndownload\nndownload.py", line 1122, in collect_parameters
    template_params["thumbnail_url"] = params["video"]["thumbnailURL"]
KeyError: 'thumbnailURL'
```

**Comment by AlexAplin** [comment]
You're using an outdated version of the script. https://github.com/AlexAplin/nndownload/blob/master/nndownload/nndownload.py#L1492

**Comment by cleartonic** [comment]
I'm not though... I downloaded it two days ago. I just redownloaded it and
I get the same error. I don't know how that line you linked to helps
clarify. I can post the params["video"] object if it's helpful. But this is
not a version problem.

**Comment by AlexAplin** [comment]
`collect_parameters` is not a function that exists in the script anymore, which this traceback indicates has been called. The line I linked shows how the `thumbnail_url` key is extracted now. Here is a random old version of the script that shows the old extraction logic, which is what your traceback shows:

https://github.com/AlexAplin/nndownload/blob/5f2a8a6e56f0bdec35344c10e483d2112e0354eb/nndownload/nndownload.py#L1398

And again, here is the new logic in the current script:
https://github.com/AlexAplin/nndownload/blob/bd8b5b8a1f5a7ae6b3545c7db84cf9f7fe8e2683/nndownload/nndownload.py#L1492
