### ISSUE TITLE
Suggestion for the wiki

### ISSUE THREAD

**Issue by dado330** [AlexAplin/nndownload#113]
I've created a simple guide on how to save links from a browser without copy and paste and then downloading them with nndownload.

https://github.com/dado330/nndownload/wiki

I don't know if you want to add it to the wiki.

**Comment by AlexAplin** [comment]
Sorry for the delay, this looks very useful! I'm reviewing it now.

**Comment by AlexAplin** [comment]
Added scripts to the wiki.
