### ISSUE TITLE
Linux issue: Change line endings to LF

### ISSUE THREAD

**Issue by senneh** [AlexAplin/nndownload#115]
I get the following error on Linux

```
$ nndownload.py
/usr/bin/env: ‘python\r’: No such file or directory
```

This happens because the first line of nndownload.py, `#!/usr/bin/env python`, has 'CRLF' line endings instead of just 'LF'.
The solution would be to convert the entire project to use LF line endings. 

Python itself does not care about line endings, but the shebang line does. 
Everything will still work on Windows while also making Linux users happy.

**Comment by senneh** [comment]
On further inspection this seems to a problem only with the pip version. When I clone the repo it seems to work just fine.

Either git does conversions on your machine or pip does when you publish your package.

**Comment by AlexAplin** [comment]
The repo behaves how I'd like, which is commiting with Linux endings and converting on checkout. 

Now to the package, I could change it to Linux endings, but won't that equally affect Windows users? I assume just LF is more portable but need to investigate.

**Comment by AlexAplin** [comment]
LF used in the v1.12 release.
