### ISSUE TITLE
Cant input password

### ISSUE THREAD

**Issue by Steeles216000** [AlexAplin/nndownload#116]
when running the exe it dtops accepting keyboard input once you input the username, so you vant put the password in.

**Comment by senneh** [comment]
It's still accepting input, it's just not displaying it for security reasons. Just type your password and press enter.

**Comment by Steeles216000** [comment]
> It's still accepting input, it's just not displaying it for security reasons. Just type your password and press enter.

Ah, so it must be failing the login for another reason.
I assumed it was because the password, and all it ever tells me is "Login Failed" with no other text.
