### ISSUE TITLE
KeyError: 'http'

### ISSUE THREAD

**Issue by KaIZeR99-code** [AlexAplin/nndownload#123]
![image](https://user-images.githubusercontent.com/83866575/159333828-1625eda5-d377-456a-b62c-beeed4f3af5f.png)
Got an error when I try to download Crush Gear Nitro episode
https://www.nicovideo.jp/watch/so39865442

**Comment by KaIZeR99-code** [comment]
I already have the membership for the channel

**Comment by AlexAplin** [comment]
Please provide the source of the page (View Source) as an attachment.

**Comment by KaIZeR99-code** [comment]
[Source.txt](https://github.com/AlexAplin/nndownload/files/8346708/Source.txt)
Is this the correct one? Sorry I'm still to new to this kind of thing...

**Comment by AlexAplin** [comment]
This appears to use HLS as the auth type, and I just noticed it's a so# video. This is a duplicate of #102.
