### ISSUE TITLE
stuck when using multithreaded download

### ISSUE THREAD

**Issue by xyzxye** [AlexAplin/nndownload#137]
by using the parser argument: "-r", "24",
the download speed has been greatly improved (from 100kb/s to 20MB/s) witch is awesome 88888888

But I encountered such a problem:
When downloading a video from Mylist, sometimes the progress bar gets stuck at like "|####################### | 94/100 @ 13.26MB /s" and keeps like flickering?

Sometimes it stays there for a while and then completes the download, while other times it remains stuck (
However, if you stop the program and run it again, it won't get stuck anymore).
It's possible that all the threads have lost the download speed at that time?

Could we implement a validation feature?
For example, if it stays stuck at a certain percentage for more than a certain amount of time, then re-download that video.

**Comment by AlexAplin** [comment]
24 seems rather high. Does this happen when you use a more reasonable number like <5? And specifically only when downloading from mylists? That last detail would be strange.

> For example, if it stays stuck at a certain percentage for more than a certain amount of time, then re-download that video.

This probably isn't going to work because of differing download speeds.

**Comment by xyzxye** [comment]
yes, it still occurs with fewer thread sometime, but I'm not sure if it only happens when downloading from mylists.

When I download, the initial download can be completed, but sometimes I get stuck in a certain video and cannot complete this download (as I described, the progress bar stops). But when I rerun the program, I may not encounter this problem again in this certain video (although it may be stuck in another one)

**Comment by xyzxye** [comment]
Also, can I download just the audio file of a video separately?(like a file in AAC format). Or do I have to download the complete MP4 file and then convert it?

**Comment by AlexAplin** [comment]
We haven't received any more reports of this and I have yet to encounter it. Given that we are transitioning to DMS (#139), which will eventually eliminate the DMC download flow, I'm going to close this as outdated.
