### ISSUE TITLE
the exe window auto closed after logged in 

### ISSUE THREAD

**Issue by LuoTianHua** [AlexAplin/nndownload#144]
both nndownload_v1_13_1.exe and nndownload.py  after I log in it just closed and did not save the status of log in. should i log in every time i want download?  can solve this problem or i did something wrong

**Comment by AlexAplin** [comment]
-g can be used to access most videos. For anything elses that requires being logged in to access, you need to provide the login each time the command is run with -u/-p or --session-cookie.
