### ISSUE TITLE
Premium Videos Support

### ISSUE THREAD

**Issue by Takashimii** [AlexAplin/nndownload#145]
Premium videos are apparently no longer downloadable and throw the error (using an account with a Premium channel subscription):

`FormatNotAvailableException: Video requires payment or membership to download`

The issue appeared around the end of February. I am not sure if this is related to the new DMS format or it's from my end.

**Comment by AlexAplin** [comment]
Can you provide an example ID(s)?

**Comment by Takashimii** [comment]
Example: https://www.nicovideo.jp/watch/so43439956

But before doing unnecessary testing, I want to make sure if a niconico Premium account is required alongside with the Channel subscription to use nndownload. I just remembered that I cancelled my niconico Premium subscription so it may be the cause. It's either that or the recent changes niconico made.

**Comment by AlexAplin** [comment]
Premium videos are generally not supported for download (#102) so I would be surprised to know they worked and I'm not sure if this is really distinct from that issue. If you have an example of a video that worked previously, does it still work for download now?

**Comment by Takashimii** [comment]
I tested with an older video and it still works. Premium videos with a channel subscription. This is the example I tested: https://www.nicovideo.jp/watch/so43263922.
And if not mistaking, it's using the new DMS based on the requests (at least it's not the usual m3u8 playlist link format since I'm seeing the new parameter (?) "Key-Pair-Id"). I'm not familiar with such stuff so if you need me to get some more details I would be glad to help.

**Comment by AlexAplin** [comment]
Yeah DMS uses that. Sounds like maybe it's being served exclusively on DMS, if it's hitting that final `else` block and DMC isn't defined. I was pretty sure standard videos aren't *exclusively* DMS at this point, but I guess it might be different for premium content.

**Comment by Takashimii** [comment]
Makes sense. They're probably fully switching to DMS and starting with Premium content.
Anyways, if by any chances there is a possible update to support such videos, it would be greatly appreciate. I somehow got used to the leisure of downloading and watching offline on the move. I can privately share my logs for the Premium account (+ e-mail forward for the 2FA) with a tip obviously :)
Just let me know otherwise this conversation can be closed. Thank you for your time and efforts !

**Comment by AlexAplin** [comment]
You can try with #146 and let me know if that works at all, it's pretty barebones right now but I think it would work enough to verify if premium content can be downloaded.

**Comment by Takashimii** [comment]
#146 seems to work. Just had to run it under C: (on Windows) since the paths are missing the "/" and results in a failure to read the key file.

**Comment by AlexAplin** [comment]
Great, I'll close this out then and you can follow progress for that on #139. Thanks!
