### ISSUE TITLE
Pass proxy in on DMS downloads

### ISSUE THREAD

**Issue by AlexAplin** [AlexAplin/nndownload#150]
We don't pass `ffmpeg -http-proxy` currently. Don't think this prevents or blocks anything currently, but we should honor it when specified. 

No support for SOCKS proxies: https://trac.ffmpeg.org/ticket/5776

UPDATE: We use the session again when performing HLS downloads in #159, so this should work as expected. Needs verification.

**Comment by fireattack** [comment]
From what I can see, the new hls_dl should already support proxies since it reuses the session we have which has `.proxies` updated with CLI arguments. 

Needs someone to test it.

**Comment by AlexAplin** [comment]
@xyzxye  Maybe you can test if you're available?

**Comment by xyzxye** [comment]
Yes! HLS downloader can function normally with a proxy (without TUN), whether through source code or CLI.
Thank your for your work!!!
