### ISSUE TITLE
Build Windows binaries with action

### ISSUE THREAD

**Issue by kagekiyo7** [AlexAplin/nndownload#153]
It will only be kept for a maximum of 90 days, but please consider it.

https://github.com/marketplace/actions/pyinstaller-windows
or
https://github.com/marketplace/actions/build-executables-or-extension-modules-from-python-projects

**Comment by AlexAplin** [comment]
Artifacts published, will be included on major releases

**Comment by kagekiyo7** [comment]
Thank you.
For now the windows binary seems to occur error.

```
Traceback (most recent call last):
  File "src\nndownload.py", line 24, in <module>
ModuleNotFoundError: No module named 'aiohttp'
[11580] Failed to execute script 'nndownload' due to unhandled exception!
```

**Comment by AlexAplin** [comment]
Should be fixed now.

**Comment by kagekiyo7** [comment]
occur this error next.
```
Traceback (most recent call last):
  File "src\nndownload.py", line 33, in <module>
ModuleNotFoundError: No module named 'ffmpeg_dl'
[21920] Failed to execute script 'nndownload' due to unhandled exception!
```

**Comment by kagekiyo7** [comment]
Rewriting like this to it will make it an absolute path, which I think resolve the problem. (in nndownlod.py)
`from src.ffmpeg_dl import FfmpegDL, FfmpegDLException`
