### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kaz-scripts** [AlexAplin/nndownload#160]
pip install git+https://github.com/AlexAplin/nndownload
and
nndownload -u "email" -p "password"

Then I got this error.

Logging in...
IndexError: list index out of range

What should I do?

**Comment by kaz-scripts** [comment]
also
nndownload --session-cookie cookies.json

Using provided session cookie.
Session cookie read from file.
AuthenticationException: Failed to login. Please verify your session cookie

I think cookies are valid

**Comment by AlexAplin** [comment]
First sounds potentially like #130. When providing a session cookie, you need to provide the bare string in the .txt or directly on the CLI.

```
  --session-cookie COOKIE
                        user_session cookie value (string or filepath)
```

**Comment by kaz-scripts** [comment]
In what format should I write user_session_XXXX...?

**Comment by kaz-scripts** [comment]
ok requests.Session

**Comment by kaz-scripts** [comment]
Nevermind, I tried it after logging out and it worked.
