### ISSUE TITLE
failed to download anime.

### ISSUE THREAD

**Issue by kaz-scripts** [AlexAplin/nndownload#162]
C:\>nndownload --session-cookie "cookie.txt" https://www.nicovideo.jp/watch/so43622101
Using provided session cookie.
Session cookie read from file.
Retrieving video manifest...
Retrieved video manifest.
Collecting video media URIs...
Collected video media URIs.
Downloading so43622101 to "so43622101 - ブルーアーカイブ The Animation 1話「アビドス高等学校 廃校対策委員会」.mp4"...
so43622101   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1,421  [ 0:00:00 < -:--:-- , ? seg/s ]
FormatNotAvailableException: ffmpeg failed to download the video or audio stream with the following error: ""

i'm premium user.
https://github.com/AlexAplin/nndownload/issues/102
Is this the specification?

**Comment by xyzxye** [comment]
yeah, this "FormatNotAvailableException" same as #161

**Comment by AlexAplin** [comment]
I doub tthat is the same as the errors in #161, it should be #102.
