### ISSUE TITLE
DMS won't download non-highest quality even if `-f` is not used

### ISSUE THREAD

**Issue by fireattack** [AlexAplin/nndownload#163]
I was testing #161 and find out I cannot even reach video download with `-g` due to not having highest quality available as a guest.

Since it defaults to "highest" here if `_cmdl_opts.video_quality` is None:

https://github.com/AlexAplin/nndownload/blob/8aa6749cb798b6ef47d97d53806b05ae0cbc6978/nndownload/nndownload.py#L1556-L1561

.. it will raise error in `select_quality()` even if `_cmdl_opts.force_high_quality` is not set.

https://github.com/AlexAplin/nndownload/blob/8aa6749cb798b6ef47d97d53806b05ae0cbc6978/nndownload/nndownload.py#L1491-L1495

I'm now curious how you guys can run it without issue.

**Comment by AlexAplin** [comment]
Most people aren't really using `-g` I suspect, and it's new with DMS download. Easy fix though!
