### ISSUE TITLE
Native HLS downloader video and audio progress bars not hitting 100% correctly

### ISSUE THREAD

**Issue by Prcuvu** [AlexAplin/nndownload#165]
It seemed that the video and audio streams were downloaded successfully, but the progress bars failed to hit 100% before the next step.

* Version: 4f2a5fc4510ced1c3d8e4f136b82a3e822057910
* Screenshot:
![image](https://github.com/AlexAplin/nndownload/assets/7923857/9796fb84-6dd9-4be8-90d1-98afe183b17f)

**Comment by AlexAplin** [comment]
Are you sure this is the commit you quoted? The progress bars for video and audio download look like they're using `tqdm.rich`, but we switched to using `rich.Progress` with the introduction of the HLS downloader in feda112b781aeee8f328c6b63ea19149232e4c31.

For example, this is how the progress bars look now (notice no `Downloading` prefix and the lack of segment info):

![image](https://github.com/AlexAplin/nndownload/assets/547786/f2c24e49-9452-43f2-b2ce-2a0bf314528c)

**Comment by Prcuvu** [comment]
I cleaned site-packages and rebuilt, and the progress bars looked fine now.

![image](https://github.com/AlexAplin/nndownload/assets/7923857/72fa7966-130c-4aee-8008-7dcb799bc182)
