### ISSUE TITLE
Seiga thumbnail template string raises warning

### ISSUE THREAD

**Issue by Prcuvu** [AlexAplin/nndownload#167]
* Commit: b58f6f73c3d26c85697b87460c23ecb024139945
* Python version: 3.12.3
* Warning message:

```
/path/to/nndownload.py:704: SyntaxWarning: invalid escape sequence '\:'
```

**Comment by AlexAplin** [comment]
New warning in 3.12: https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes
