### ISSUE TITLE
Support downloading from Re:Kari

### ISSUE THREAD

**Issue by EE12450** [AlexAplin/nndownload#173]
Hello, is your nndownload available on the makeshift website of Niconico, I think the video of this site is very interesting and I want to download it

**Comment by AlexAplin** [comment]
All of these videos are mirrors of existing videos that will come back when the site recovers. I am considering adding comment download support: #172

**Comment by AlexAplin** [comment]
Unfortunately my VPN is now blocked and I'm getting a 403. Endpoints if someone would like to work on this:

Roll ten videos for the frontpage gacha: https://nvapi.nicovideo.jp/v1/tmp/videos?count=10&_frontendId=6&_frontendVersion=0.0.0
Video comments: https://nvapi.nicovideo.jp/v1/tmp/comments/sm982882?_frontendId=6&_frontendVersion=0.0.0
POST endpoint for video HLS data: https://nvapi.nicovideo.jp/v1/tmp/watch/sm982882/access-rights/hls?actionTrackId=eNKTcnpbq8_1718544747044&_frontendId=6&_frontendVersion=0.0.0

**Comment by AlexAplin** [comment]
Endpoints if someone would like to work on this:

Roll ten videos for the frontpage gacha: https://nvapi.nicovideo.jp/v1/tmp/videos?count=10&_frontendId=6&_frontendVersion=0.0.0
Video comments: https://nvapi.nicovideo.jp/v1/tmp/comments/sm982882?_frontendId=6&_frontendVersion=0.0.0
POST endpoint for video HLS data: https://nvapi.nicovideo.jp/v1/tmp/watch/sm982882/access-rights/hls?actionTrackId=eNKTcnpbq8_1718544747044&_frontendId=6&_frontendVersion=0.0.0

**Comment by AlexAplin** [comment]
Re:Kari will be discontinued on August 5th when the site relaunches (#172), so I'm closing this
