### ISSUE TITLE
Can't download manga

### ISSUE THREAD

**Issue by Z-fly** [AlexAplin/nndownload#189]
import nndownload

url = "https://manga.nicovideo.jp/watch/mg846132"
output_path = "/tmp/{id}.{ext}"
nndownload.execute( "-y socks5://127.0.0.1:7890","-o", output_path, url)

![image](https://github.com/user-attachments/assets/2efb245f-f294-402a-9168-1bccf57cea99)

**Comment by AlexAplin** [comment]
`-y socks5://[...]`

#176, or you need to login by passing `--session-cookie` or `-u`. This example works successfully on my end

```
nndownload --session-cookie user_session_[...] "https://manga.nicovideo.jp/watch/mg846132"
Using provided session cookie.
Session cookie read as string.
Downloading mg846132 to "69189 - 飛び降りる直前の同級生に「×××しよう！」と提案してみた。/mg846132 - 第1話"...
Page 3/29
```
