### ISSUE TITLE
Please escape characters that can not be used for file names

### ISSUE THREAD

**Issue by f11894** [AlexAplin/nndownload#26]
For example, these videos.

『 Antinomie 』/ ELECTROCUTICA
http://www.nicovideo.jp/watch/sm33004336

TGM3 SHIRASE(W) 3:53:85
http://www.nicovideo.jp/watch/sm33307637

**Comment by AlexAplin** [comment]
As mentioned in #1, illegal characters depend on the platform. I will add some general support.
