### ISSUE TITLE
Multi-threaded downloading

### ISSUE THREAD

**Issue by Aruelius** [AlexAplin/nndownload#32]
Because nicovideo is a paid member, single-threaded speed limit, but if you use multi-threading, you can achieve very fast speed.

**Comment by Aruelius** [comment]
This is the difference between single-threaded and multi-threaded download speeds.
![image](https://user-images.githubusercontent.com/25380989/50887554-7249c880-142e-11e9-9853-e56145a1a64d.png)

**Comment by AlexAplin** [comment]
I'll do some testing to see if this is viable in practice for all video types.

**Comment by Aruelius** [comment]
Ok, thank you very much.

**Comment by AlexAplin** [comment]
@Aruelius I added this and it works for all video types. It's definitely a lot faster! Currently it doesn't show download progress.
