### ISSUE TITLE
Does not fail gracefully with live URL

### ISSUE THREAD

**Issue by Etherrrr** [AlexAplin/nndownload#33]
After I logged in with`python nndownload.py -u [username] -p [password] -o [output directory] [url]`, it just showed
```
Logging in...
Logged in.
```
and nothing comes out and seems the recorder doesn't work.

After I deleted the `-o` segement, it comes error like
```
Traceback (most recent call last):
  File "nndownload.py", line 713, in main
    process_url_mo(session, url_mo)
  File "nndownload.py", line 678, in process_url_mo
    request_rtmp(session, url_id)
  File "nndownload.py", line 176, in request_rtmp
    urls = urllib.parse.unquote(nama_info.getElementsByTagName("contents")[0].firstChild.nodeValue).split(",")
IndexError: list index out of range
```
How to fix this?

**Comment by AlexAplin** [comment]
According to the trace, you were trying to request a live URL. [We don't currently support downloading timeshifts](https://github.com/AlexAplin/nndownload/issues/11), so the `-o` flag will do nothing and this is expected behavior.
