### ISSUE TITLE
Video page rate limiting

### ISSUE THREAD

**Issue by Suika** [AlexAplin/nndownload#40]
Restarting the script on user/mylist that has more than 50 entries, will cause the script to run into rate limit that is imposed on the video pages. The reported error is: `requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.nicovideo.jp/watch/sm...`
The options used to run the script are: `--dump-metadata --download-thumbnail --download-comments --force-high-quality`

Example:
I archive a user that has exactly 50 entries. After all videos are archived, I restart the script with the same parameters.
Depending on the mood of NND after approximately 3 minutes and 30 second, and between fetching the 43rd-47th video, NND will respond with a 503 error.

The video page will be available after 30-60 seconds.

Suggestion:
If the script encounters a 503 error, catch that exception and wait 60 seconds before restarting the download, is possible multiple(3) retries.
Optionally, have a flag that allows to define wait time, otherwise a global variable that the user can edit inside the script.

**Comment by AlexAplin** [comment]
I'll implement a cooldown with global variables for number of retries and timeout. When I get to the class rewrite, this'll be more user friendly.
