### ISSUE TITLE
Nico Seiga support

### ISSUE THREAD

**Issue by 0xh3LL0** [AlexAplin/nndownload#56]

**Comment by AlexAplin** [comment]
Nico Seiga links? A few downloaders I know support individual images and comics. I'm not sure if any support manga. Take a look [at these](https://github.com/search?q=nico+seiga). I'm not against adding support but if someone else has solved it then I'd like to prevent duplicate work.

**Comment by 0xh3LL0** [comment]
how about this:
http://seiga.nicovideo.jp/watch/mg173049

and actually i've tried this:
https://github.com/taba256/nicoseiga-download
but it didnt work since it didnt updated anymore

btw, only unofficial & fanmade manga can be downloaded.

**Comment by AlexAplin** [comment]
Are you sure it doesn't work? I only tested it in Firefox (68.0) with Tampermonkey (4.9.5941) but I got it to work with both official (DRM protected) and fan manga. Example links:
- http://seiga.nicovideo.jp/watch/mg309638
- http://seiga.nicovideo.jp/watch/mg357400

In any case, I think it'd be useful to have Seiga support for batch downloading, including for individual images. I'll be working on support for this if you can't get it to work, so please wait warmly!

**Comment by AlexAplin** [comment]
Official manga use a light form of DRM, decryption is controlled by ImageLoader in http://seiga.nicovideo.jp/js/manga/common.min.js. The `data-original` attribute in `img.lazyload` classes contains a binary encrypted form of each image which then gets decrypted into a Base64 string. Other manga can be retrieved without modification from the attribute URL.

```
var o = this.getKeyFromUrl(e);
t.open('GET', e, !0),
t.responseType = 'arraybuffer',
t.onload = function (t) {
var i = new Uint8Array(this.response);
'' !== o && (i = r.decrypt(i, o));
var s = r.getDataType(i),
l = r.toBase64String(i),
u = 'data:image/' + s + ';base64,' + l;
```

```
this.getKeyFromUrl = function (t) {
   var e = t.match('/image/([a-z0-9_]+)/');
   if (null === e) return '';
   var r = e[1].split('_'), n = r[0];
   return n
},
this.decrypt = function (t, e) {
   var r, n = [], a = 8;
   for (r = 0; r < a; r++) n.push(parseInt(e.substr(2 * r, 2), 16));
   for (r = 0; r < t.length; r++) t[r] = t[r] ^ n[r % a];
   return t
},
this.toBase64String = function (t) {
   var e, r = '', n = t.length;
   for (e = 0; e < n; e++) r += String.fromCharCode(t[e]);
   return Base64.btoa(r)
},
this.getDataType = function (t) {
   var e = null, r = t.length;
   return 255 === t[0] && 216 === t[1] && 255 === t[r - 2] && 217 === t[r - 1] ? e = 'jpg' : 137 === t[0] && 80 === t[1] && 78 === t[2] && 71 === t[3] ? e = 'png' : 71 === t[0] && 73 === t[1] && 70 === t[2] && 56 === t[3] && (e = 'gif'), e
}
```

**Comment by AlexAplin** [comment]
Seiga images can be retrieved at http://seiga.nicovideo.jp/image/source/<image_id> which redirects to a page using the full image.

**Comment by 0xh3LL0** [comment]
hm... thats odd, 
i'm using firefox 69 with many settings (to disable telemetry, etc) maybe i'll reset my browser and try again.

**Comment by 0xh3LL0** [comment]
confirmed, it works...

**Comment by 0xh3LL0** [comment]
> I think it'd be useful to have Seiga support for batch downloading

yes please! 
it would be usefull to download 1 page manga with many chapters like this one
http://seiga.nicovideo.jp/comic/36993

**Comment by AlexAplin** [comment]
You can now download individual chapters, full manga, and images. I'll be working on support for downloading everything from a user/uploader.
