### ISSUE TITLE
Multiple URLs

### ISSUE THREAD

**Issue by 0xh3LL0** [AlexAplin/nndownload#62]
is it possible to add feature to download multiple manga in one session?
like: nndownload URL1 URL2 so on...
niconico ban me for download 20+ manga in one time,
they must be thought me login for 20+ times as hacking attempt or something...

**Comment by AlexAplin** [comment]
I can see about suporting multiple URL arguments. If you use a file with URLs, that will perform all of the downloads using one session:

`python nndownload.py -g input.txt`

input.txt:

```
https://www.nicovideo.jp/watch/sm36308141
https://www.nicovideo.jp/watch/sm23621998
...
```
