### ISSUE TITLE
Nicoseiga CDN domain change

### ISSUE THREAD

**Issue by 0xh3LL0** [AlexAplin/nndownload#65]
still working for free manga, but not for the official one,
looks like the domain change from nicoseiga.jp to nimg.jp

![gtgtgtuuy](https://user-images.githubusercontent.com/23132217/84472438-5bf20d00-acb1-11ea-9cc7-4b425ad13c7c.png)

**Comment by AlexAplin** [comment]
You're right, `drm.nicoseiga.jp` is now `nicoseiga.cdn.nimg.jp/drm`.

**Comment by 0xh3LL0** [comment]
release please...
