### ISSUE TITLE
Download a channel's videos

### ISSUE THREAD

**Issue by gj94gj94ao4** [AlexAplin/nndownload#66]
I am a niconico channel member and I want to download all the videos on a channel.
It's possible to download one of the video on a channel.
So maybe you can add a support to fetch videos list on a channel list like below if you have some free time.

https://ch.nicovideo.jp/{channel}/video
https://ch.nicovideo.jp/{channel}/video/pay
https://ch.nicovideo.jp/{channel}/video/member

peace 🍡

**Comment by AlexAplin** [comment]
Sounds good, I'll try to add it soon.

**Comment by AlexAplin** [comment]
I added support for downloading all videos (`/video`).

**Comment by gj94gj94ao4** [comment]
Sorry bother you again.

The URL of some channels have numbers.

e.t.c
https://ch.nicovideo.jp/co1971385
https://ch.nicovideo.jp/tsukasashi2525ch

I'm not sure if it has underline also, so I don't add underline.

Here I add some pattern in it.  **0-9**
VALID_URL_RE = re.compile(r"(?:https?://(?:(?:(?:(ch|sp|www|seiga)\.)|(?:(live[0-9]?|cas)\.))?(?:(?:nicovideo\.jp\/(watch|mylist|user|comic|seiga)?)(?(3)\/|))|nico\.ms\/))((?:(?:[a-z]{2})?[0-9]+)|[**0-9**a-zA-z-]+)")

BTW I don't know how to use PR, sorry about that. :P
