### ISSUE TITLE
Download Seiga images from user

### ISSUE THREAD

**Issue by aezakmil** [AlexAplin/nndownload#69]
here is the error code

Requesting videos from user illust...
Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\nndownload\nndownload.py", line 1437, in main
    process_url_mo(session, url_mo)
  File "C:\Python37-32\lib\site-packages\nndownload\nndownload.py", line 1390, in process_url_mo
    request_user(session, url_id)
  File "C:\Python37-32\lib\site-packages\nndownload\nndownload.py", line 725, in request_user
    user_videos_page.raise_for_status()
  File "C:\Python37-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.nicovideo.jp/user/illust/video?page=1

or maybe its not support  seiga now?

**Comment by AlexAplin** [comment]
You need to post the command you're using.

**Comment by aezakmil** [comment]
Hi admin
I use module run by .py data
-
import nndownload
url = "https://seiga.nicovideo.jp/user/illust/15483033"
output_path = "/seiga/{id}/{manga_id} - {title}"
nndownload.execute("-o",output_path, url)
-
also try use CLI, the result are same

it can work on nicovideo, but fail in seiga comic and user's illust.

thanks help

**Comment by AlexAplin** [comment]
The script doesn't currently support downloading all images from a user. Because of that, I haven't adjusted the regex to check for that URL so that's why you get the strange error.

**Comment by AlexAplin** [comment]
This is supported now. By the way, `output_path = "/seiga/{id}/{manga_id} - {title}"` is for Seiga manga. If you're downloading Seiga images, you want something like `output_path = "/seiga/{uploader_id}/{id} - {title}.{ext}"`. Hope this helps.

**Comment by aezakmil** [comment]
Hi admin 
Thx your help :)
>output_path = "/seiga/{user_id}/{id} - `{title}.{ext}"

Got it!
