### ISSUE TITLE
Add metadata tags to MP4 files

### ISSUE THREAD

**Issue by Xyde** [AlexAplin/nndownload#78]
youtube-dl already does this., where it embeds metadata directly to the video container.

**Comment by AlexAplin** [comment]
We can maybe do this for MP4. FLV/SWF, I don't believe those containers support adding metadata tags beyond the basic descriptors.

**Comment by AlexAplin** [comment]
I have this implemented but unfortunately it messes with resuming on incomplete files as embedded metadata changes the file length. I'll need to think about how to handle that.

**Comment by AlexAplin** [comment]
- Write metadata to the container only when the video is done downloading
- Change how integrity is checked on redownloading videos:
  - Complete files
    - If metadata tags exist, we can be confident the file is complete; `MP4StreamInfoError` thrown if not an MP4
    - Otherwise if current size exceeds video length, server file must be of a different quality
  - Incomplete files
    - No change in behavior (can match on byte position with server)
