### ISSUE TITLE
Request new release to update Pypi package

### ISSUE THREAD

**Issue by myl7** [AlexAplin/nndownload#84]
Currently `nndownlaod` on Pypi does not include https://github.com/AlexAplin/nndownload/commit/d010e433c40def3a89753c2e9c086cd434a92f70 .
`pip install nndownload` failed for not finding requirements.txt.
I would like to suggest a new release and update the package on Pypi to allow it to be installed.

**Comment by AlexAplin** [comment]
v1.8.1 was uploaded with the most recent commit.
