### ISSUE TITLE
what about downloading without authorization?

### ISSUE THREAD

**Issue by MiTereKun** [AlexAplin/nndownload#86]
Hi, I don’t think there are many people abroad with premium accounts. The allotted time when the video is available in 720/1080 p is quite enough. I download through the service https://parsevideo.com - it gives direct links to the hosting dmc.nico where the video is available for the first 2 minutes, after which the key (hash in the link) stops working and, accordingly, the video longer than 2 cannot be downloaded directly - 403 Forbidden, and the downloaded file gets the "forbidden file" error.

And I know another Chinese service, where at first it was possible to download videos longer than 2 minutes, but then the waiting time was 3 hours, and the last time I used it, I waited a day and a half (they didn’t want to big, but still money)

Returning to dmc.nico (for example http://vodedge634.dmc.nico) - videos from it are definitely downloaded without any authorization. Need a program (maybe a simple mod for your development). The task of the program is to download 2 minutes from each link (with its unique cache) and combine parts of the video into a full-fledged final video.
It's also a nuisance that nicovideo.jp is clumsily blocked in my country by the Internet regulator due to a couple of videos with Islamic terrorists, so my attempt to log in without a proxy stops, but I still don't have a paid proxy through which I could send traffic to the entire system and CMD
<details><summary>screen</summary><img src="https://user-images.githubusercontent.com/32958490/102681972-64ec0a00-4211-11eb-9c81-d1a3e0533f50.PNG"></details>

<details><summary>original text</summary>привет, не думаю что за границей есть много людей с премиум аккуантами. Отведённого времени, когда видео доступно в 720/1080 p вполне достаточно. Я скачиваю через сервис https://parsevideo.com - он выдаёт прямые ссылки на хостинг dmc.nico где видео доступно первые 2 минуты, после чего ключ (хеш в ссылке) перестаёт работать и соответственно видео дольше 2-х напрямую скачать невозможно - 403 Forbidden, а у скачиваемого файла возникает ошибка "запрещённый файл". <br><br>И знаю ещё один китайский сервис, где вроде раньше получалось скачивать видео дольше 2-х минут, но сначало время ожидание было 3 часа, в конце когда я им пользовался - за полтора дня (за скорость и снятие лимита они хотели не больших, но всё же денег) <br><br>Возвращаясь к dmc.nico - видео с него точно скачиваются без какой-либо авторизации. Нужна программа (может быть простой мод к вашей разработки). Программа задача которой качать 2 минуты с каждой ссылки (с её уникальным кешем) и соединять части видео в полноценное конечное видео.</br>Так же неприятность заключается в том, что nicovideo.jp топорно заблокирован в моей стране интернет-регулятором из-за пары видео с исламскими террористами, по этому у меня обрывается попытка авторизоваться без прокси, а у меня всё ещё нет платного прокси, через который я бы мог пустить трафик во всю систему и CMD</details>

GIST - please make a simple video parts combiner with dmc.nico. Thank you

**Comment by AlexAplin** [comment]
The  -g/--no-login flag is available for downloading without authorization, so I'm closing this as a duplicate. When using -g, files are downloaded through DMC servers (dmc.nico) when available. Example usage:

`nndownload.exe -g https://www.nicovideo.jp/watch/sm33064837`

If I misunderstood your request, please clarify it again so I can take a look.
