### ISSUE TITLE
How to use the windows version of the release page

### ISSUE THREAD

**Issue by Vstory** [AlexAplin/nndownload#91]
After I run nndownload_v1_8_1.exe, in the command line window of the pop-up window, after inputting the account password, the window will automatically close.

I run it in powershell 
`.\nndownload_v1_8_1.exe   input url = "https://live2.nicovideo.jp/watch/example" output_path=C:\Users\1\Downloads\Programs\1.mp4  -u username -p password -r 5 -f -a`
it will report errors.

I really need to use it, is there any reference information? Thank you

**Comment by AlexAplin** [comment]
You aren't using flags or positional arguments correctly.

` nndownload_v1_8_1.exe https://live2.nicovideo.jp/watch/example -o "C:\Users\1\Downloads\Programs\1.mp4" -u username -p password -r 5 -f -a`

**Comment by Vstory** [comment]
> nndownload_v1_8_1.exe https://live2.nicovideo.jp/watch/example -o "C:\Users\1\Downloads\Programs\1.mp4" -u username -p password -r 5 -f -a


Thank you
