### ISSUE TITLE
[24448] Failed to execute script nndownload

### ISSUE THREAD

**Issue by Xyde** [AlexAplin/nndownload#92]
>nndownload_v1_8_2.exe https://www.nicovideo.jp/user/53610183 -o{uploader_id}" - "{uploader}\{published}{title}{id}.{ext} -u USERNAME -p PASSWORD -r 5 -f -a

Returns

>ModuleNotFoundError: No module named 'requests'
[24448] Failed to execute script nndownload

**Comment by AlexAplin** [comment]
Replaced binary.
