### ISSUE TITLE
Playlist index start/reverse order

### ISSUE THREAD

**Issue by psydere** [AlexAplin/nndownload#98]
When I run nndownload, I split downloading the video and the thumbnail in two parts (I download videos during low traffic and the thumbnail and json file during high traffic). However, when I download thumbnail and whatnot after the 39th or 40th "video" I always get this error: requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url. (This also happens when I do not skip media but much more prevalent when I split it)

It's annoying but I'm ok with restarting the queue from the beginning however it infinitely gets stalled at that number. So when I download a user that has more than a hundred video I can never get the all the files from the playlist.

A workaround I think that be used is to add the --reverse-playlist command that for youtube-dl uses, or enable the user to start downloading the queue at the 40th video specifically instead of parsing all the info from the beginning.

**Comment by AlexAplin** [comment]
I'm adding `--playlist-start` to specify the index and probably `--reverse` at some point.
