### ISSUE TITLE
Retrieving output filename

### ISSUE THREAD

**Issue by jamesWalker55** [AlexAplin/nndownload#99]
I'm writing a Python program that uses `nndownload`, but I need a way to get the path to the output file after downloading has finished. The output template I'm using is `"download.{ext}"`.

```python
nndownload.execute(
    "-u", username,
    "-p", password,
    "-o", "download.{ext}",
    "--force-high-quality",
    url,
)
```

Is there any way to get the output filename?

**Comment by AlexAplin** [comment]
This isn't something I plan to support. You can redirect `stdout` or something similar: https://stackoverflow.com/questions/22822267/how-to-capture-print-output-of-another-module

Based on your `"-o", "download.{ext}"` your path is going to be `download.mp4` always and the absolute path being the directory the script is being run from.
